### ISSUE TITLE
Unable to build on iOS: No visible @interface for 'UIImage' declares the selector 'imageByPreparingForDisplay'

### ISSUE THREAD

**Issue by getpoucher** [fluttercandies/flutter_image_compress#215] opened 2022-07-09 01:22 UTC
Hello,

I'm using flutter 2.10.5 and I'm trying to build to iOS 15.5, but I'm having the following error:

```
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No visible @interface for 'UIImage' declares the selector 'imageByPreparingForDisplay'
~/app/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:373:39


ARC Semantic Issue (Xcode): No visible @interface for 'UIImage' declares the selector 'imageByPreparingThumbnailOfSize:'
~/app/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:441:39
```

**Comment by MapperMalte** [comment] 2022-07-18 23:52
Getting something similar

    ../ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:31:40: error: no visible @interface for 'UIImage' declares the selector 'imageByPreparingForDisplay'
            UIImage *decodedImage = [image imageByPreparingForDisplay];
                                     ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~
    ../ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:48:40: error: no visible @interface for 'UIImage' declares the selector 'imageByPreparingThumbnailOfSize:'
            UIImage *decodedImage = [image imageByPreparingThumbnailOfSize:thumbnailSize];
                                     ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by AlexV525** [comment] 2022-08-03 03:53
The issue seems to be related to `SDWebImage`, please verify if the example can reproduce the problem. Otherwise, run `pod install` and make sure everything is installed correctly.

**Comment by AlexV525** [comment] 2022-08-03 08:06
Tested with the example and no issues occurred. Closing.

**Closed by AlexV525** 2022-08-03 08:06 UTC
Labels: await response
